# Generated by Django 5.0 on 2024-01-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviews',
        ),
    ]
