# Generated by Django 5.0 on 2024-01-13 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_remove_book_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 17, 26, 49, 98002, tzinfo=datetime.timezone.utc)),
        ),
    ]
