# Generated by Django 5.0 on 2024-01-14 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_borrowinghistory_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 5, 52, 8, 614446, tzinfo=datetime.timezone.utc)),
        ),
    ]
