# Generated by Django 5.0 on 2024-01-14 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_borrowinghistory_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 6, 38, 29, 94700, tzinfo=datetime.timezone.utc)),
        ),
    ]
