# Generated by Django 5.0 on 2024-01-14 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0007_alter_borrowinghistory_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 7, 34, 41, 321387, tzinfo=datetime.timezone.utc)),
        ),
    ]
