# Generated by Django 5.0 on 2024-01-16 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_alter_borrowinghistory_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 6, 0, 49, 646674, tzinfo=datetime.timezone.utc)),
        ),
    ]
