# Generated by Django 5.0 on 2024-01-17 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0009_alter_borrowinghistory_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 4, 26, 40, 255524, tzinfo=datetime.timezone.utc)),
        ),
    ]
