# Generated by Django 5.0 on 2024-02-26 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0010_alter_borrowinghistory_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='returned_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 5, 32, 11, 941524, tzinfo=datetime.timezone.utc)),
        ),
    ]
